### ISSUE TITLE
Compose remain running in case of Junit Tests failures

### ISSUE THREAD

**Issue by MarcoMontel** [br4chu/docker-compose-maven-plugin#11]
Assuming this configuration 

            <plugin>
                <groupId>io.brachu</groupId>
                <artifactId>docker-compose-maven-plugin</artifactId>
                <version>0.9.0</version>
                <executions>
                    <execution>
                        <id>clean-before-up</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>down</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>up</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>up</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>down</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>down</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

The down goal seems not to work properly because it is not able to handle the fact that at first execution the cluster is not running.

`Execution clean-before-up of goal io.brachu:docker-compose-maven-plugin:0.9.0:down failed: Cluster is not up -> [Help 1]`

**Comment by mjagus** [comment]
This is now fixed in v0.11.0. As a workaround for older versions, one can disable `killBeforeDown` property of `down` goal.
