### ISSUE TITLE
Condition with lambda expression in io.brachu.johann.cli.DockerComposeCli was not fulfilled

### ISSUE THREAD

**Issue by dcheng45** [br4chu/docker-compose-maven-plugin#4]
We have been using this plugin for running our integration tests. Up until now we've been using version 0.1.0. I'm upgraded to docker desktop 2.1.0.3 and I'm running into the following issue:

Failed to execute goal io.brachu:docker-compose-maven-plugin:0.6.0:up (start-compose) on project ispws: Docker-compose cluster failed to start: Timed out while waiting for cluster to be healthy. Condition with lambda expression in io.brachu.johann.cli.DockerComposeCli was not fulfilled within 240 seconds. TimeoutException

I've upgraded the plugin to 0.6.0 and still get the same error. Doesn't matter if I extend the wait time. The health check on the web container says it is healthy before it reaches the end of the wait time.

**Comment by mjagus** [comment]
Maybe one of your containers can't start properly after upgrading?
Can you provide a minimalistic docker-compose file that replicates the issue?

**Comment by dcheng45** [comment]
I've given up on this. Possibly caused by updated my mac to Catalina. I needed to downgrade to previous OS and install previous version of docker
