### ISSUE TITLE
Support remote commands

### ISSUE THREAD

**Issue by OakLi** [br4chu/docker-compose-maven-plugin#9]
If I want to use this plugin, is it necessary to install docker-compose locally?

**Comment by mjagus** [comment]
Yes, both Maven process that runs this plugin and docker-compose must be on the same machine. AFAIR docker-compose doesn't expose any API that allows to communicate with it remotely but it's possible to communicate with docker remotely via docker-compose by passing DOCKER_HOST environment variable to docker-compose CLI. This can actually be done from this plugin.
